### ISSUE TITLE
Fatal error when weight is zero or when the order contains virtual products

### ISSUE THREAD

**Issue by patrick-leb** [flagshipcompany/flagship-for-woocommerce-bedrock#17]
```
2021/07/28 15:56:14 [error] 499#499: *85664 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get_weight() on bool in /var/www/html/wordpress/web/app/plugins/flagship-for-woocommerce-bedrock/includes/Helpers/Package_Helper.php:54
Stack trace:
#0 /var/www/html/wordpress/web/app/plugins/flagship-for-woocommerce-bedrock/includes/Helpers/Package_Helper.php(17): FlagshipWoocommerceBedrock\Helpers\Package_Helper->extract_items()
#1 /var/www/html/wordpress/web/app/plugins/flagship-for-woocommerce-bedrock/includes/Requests/Export_Order_Request.php(114): FlagshipWoocommerceBedrock\Helpers\Package_Helper->make_packages()
#2 /var/www/html/wordpress/web/app/plugins/flagship-for-woocommerce-bedrock/includes/Requests/Export_Order_Request.php(35): FlagshipWoocommerceBedrock\Requests\Export_Order_Request->makePrepareRequest()
#3 /var/www/html/wordpress/web/app/plugins/flagship-for-woocommerce-bedrock/includes/Order_Action_Processor.php(400): FlagshipWoocommerceBedrock\Requests\Export_Order_Request->exportOrder()
```

**Comment by patrick-leb** [comment]
Actually, the error happens when the product exists in the order but has been deleted from the inventory. Better error handling in this situation would be nice.
